# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#home'
    weight: 10
  - name: Projects
    url: 'project'
    weight: 20
  - name: Publications
  #  parent: 'Publications'
    url: 'publications'
    weight: 30
  - name: Open Science
    url: 'open_science'
    weight: 35
  - name: Collaborations
    url: 'collaborations'
    weight: 40
  - name: Teaching
    url: 'teaching'
    weight: 50
  - name: In the media
    parent: "Other"
    url: 'other/media'
    weight: 2
  - name: Other activities
    parent: "Other"
    url: 'other/other_activities'
    weight: 1  
  - name: Funding
    parent: "Other"
    url: 'other/funding'
    weight: 3
  - name: Gallery
    parent: "Other"
    url: 'other/gallery'
    weight: 4
  - name: Contact
    url: 'contact/'
    weight: 80


    
    
#  - name: "Current lab members"
#    parent: "People"
#    url: "people/people"
#    weight: 1
#  - name: "Former lab members"
#    parent: "People"
#    url: "people/alumni"
#    weight: 2
#  - name: "Collaborators & Visitors"
#    parent: "People"
#    url: "people/visiting"
#    weight: 3
