# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Demo
#    url: '#about'
#    weight: 10
 
  - name: Projects
    url: 'project'
    weight: 20  
  - name: Publications
    url: 'publication/publications'
    weight: 30
  - name: Collaborations
    url: 'collaborations/collaborations'
    weight: 40
  - name: Gallery
    url: 'gallery/gallery'
    weight: 50  
  - name: Posts
    url: '#posts'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70

    
    
#  - name: "Current lab members"
#    parent: "People"
#    url: "people/people"
#    weight: 1
#  - name: "Former lab members"
#    parent: "People"
#    url: "people/alumni"
#    weight: 2
#  - name: "Collaborators & Visitors"
#    parent: "People"
#    url: "people/visiting"
#    weight: 3
